/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg2_josezuniga_31841432;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;

/**
 *
 * @author josez
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        usuarios.leerArchivo();
        for (Usuarios user : usuarios.getUsers()) {
            for (Videos video1 : user.getCanal().getVideos()) {
                System.out.println(video1);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearUsuario = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        creaNom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        creaCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        creaEdad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        creaUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        creaCanal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        creaCat = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        creaPass = new javax.swing.JPasswordField();
        vistaPrincipal = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCanales = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbolito = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        menuListaCanales = new javax.swing.JPopupMenu();
        subscribir = new javax.swing.JMenuItem();
        videosDiag = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        videoNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        videoTiempo = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        subirVideo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        videoArea = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        subtit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        menuarbol = new javax.swing.JPopupMenu();
        Ver = new javax.swing.JMenuItem();
        verVideo = new javax.swing.JDialog();
        videoBarra = new javax.swing.JProgressBar();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaVerVideo = new javax.swing.JTextArea();
        nombreVideo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        logPass = new javax.swing.JPasswordField();

        jLabel4.setText("Nombre");

        jLabel5.setText("Correo");

        jLabel6.setText("Edad");

        creaEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel7.setText("Usuario");

        jLabel8.setText("Contraseña");

        jLabel9.setText("Canal");

        jLabel10.setText("Categoria");

        creaCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juegos", "Deportes", "Cocina", "Vlogs", "Musica" }));

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        creaPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crearUsuarioLayout = new javax.swing.GroupLayout(crearUsuario.getContentPane());
        crearUsuario.getContentPane().setLayout(crearUsuarioLayout);
        crearUsuarioLayout.setHorizontalGroup(
            crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearUsuarioLayout.createSequentialGroup()
                .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crearUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(creaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crearUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(crearUsuarioLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(creaNom, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(68, 68, 68)
                                            .addComponent(jLabel5))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearUsuarioLayout.createSequentialGroup()
                                            .addGap(187, 187, 187)
                                            .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel8))))))
                            .addGroup(crearUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(creaCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creaCorreo)
                            .addComponent(creaUser)
                            .addComponent(creaCat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creaPass, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                    .addGroup(crearUsuarioLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton3)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        crearUsuarioLayout.setVerticalGroup(
            crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearUsuarioLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(creaNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(creaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(creaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(creaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(creaPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(creaCanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(creaCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jButton3)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jLabel11.setText("Canales -Todos-");

        listaCanales.setModel(new DefaultListModel());
        listaCanales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCanalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCanales);

        jLabel12.setText("Mis Subscripciones");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Canales");
        arbolito.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbolito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolitoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(arbolito);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Canales", jPanel1);

        jButton4.setText("Subir Video");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(515, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mi Canal", jPanel2);

        javax.swing.GroupLayout vistaPrincipalLayout = new javax.swing.GroupLayout(vistaPrincipal.getContentPane());
        vistaPrincipal.getContentPane().setLayout(vistaPrincipalLayout);
        vistaPrincipalLayout.setHorizontalGroup(
            vistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        vistaPrincipalLayout.setVerticalGroup(
            vistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vistaPrincipalLayout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        subscribir.setText("subscribir");
        subscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribirActionPerformed(evt);
            }
        });
        menuListaCanales.add(subscribir);

        jLabel13.setText("Nombre");

        jLabel14.setText("Tiempo de reproduccion");

        videoTiempo.setModel(new javax.swing.SpinnerNumberModel(10, 10, null, 1));

        jLabel15.setText("Segundos");

        subirVideo.setText("Subir Video");
        subirVideo.setEnabled(false);
        subirVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirVideoActionPerformed(evt);
            }
        });

        videoArea.setColumns(20);
        videoArea.setLineWrap(true);
        videoArea.setRows(5);
        jScrollPane3.setViewportView(videoArea);

        jLabel16.setText("Subtitulo");

        subtit.setText("Añadir");
        subtit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout videosDiagLayout = new javax.swing.GroupLayout(videosDiag.getContentPane());
        videosDiag.getContentPane().setLayout(videosDiagLayout);
        videosDiagLayout.setHorizontalGroup(
            videosDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, videosDiagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(subirVideo)
                .addGap(21, 21, 21))
            .addGroup(videosDiagLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(videosDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel16)
                    .addGroup(videosDiagLayout.createSequentialGroup()
                        .addGroup(videosDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(videosDiagLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(27, 27, 27)
                                .addComponent(videoTiempo))
                            .addGroup(videosDiagLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(videoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addComponent(subtit)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        videosDiagLayout.setVerticalGroup(
            videosDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videosDiagLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(videosDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(videoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(videosDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(videoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(31, 31, 31)
                .addComponent(jLabel16)
                .addGroup(videosDiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(videosDiagLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, videosDiagLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(subtit)
                        .addGap(147, 147, 147)))
                .addComponent(subirVideo)
                .addContainerGap())
        );

        Ver.setText("Ver video");
        Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerActionPerformed(evt);
            }
        });
        menuarbol.add(Ver);

        jButton5.setText("Play");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        areaVerVideo.setColumns(20);
        areaVerVideo.setRows(5);
        jScrollPane4.setViewportView(areaVerVideo);

        nombreVideo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout verVideoLayout = new javax.swing.GroupLayout(verVideo.getContentPane());
        verVideo.getContentPane().setLayout(verVideoLayout);
        verVideoLayout.setHorizontalGroup(
            verVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)
                        .addComponent(videoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombreVideo))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        verVideoLayout.setVerticalGroup(
            verVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verVideoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(nombreVideo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(videoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(23, 23, 23))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("LogIn");

        jLabel2.setText("Usuario");

        jLabel3.setText("Password");

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear Usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logUser)
                            .addComponent(logPass, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton2)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(logUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(logPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        crearUsuario.pack();
        crearUsuario.setLocationRelativeTo(this);
        crearUsuario.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nombre, correo, usuario, contraseña;
        int edad;
        try {
            nombre = creaNom.getText();
            correo = creaCorreo.getText();
            usuario=creaUser.getText();
            contraseña = creaPass.getText();
            String nombreCanal = creaCanal.getText();
            String categoria = creaCat.getSelectedItem().toString();
            Canales ca = new Canales(nombreCanal, categoria);
            edad = Integer.parseInt(creaEdad.getValue().toString());
            Usuarios use = new Usuarios(nombre, correo, usuario, ca, contraseña, edad);
            usuarios.setUser(use);
            usuarios.guardarArchivo();
            creaNom.setText("");
            creaCanal.setText("");
            creaPass.setText("");
            creaUser.setText("");
            creaEdad.setValue(0);
            creaCorreo.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (Usuarios user : usuarios.getUsers()) {
            System.out.println(user);
            if (user.getUsuario().equals(logUser.getText()) && user.getContraseña().equals(logPass.getText())) {
                usuarioSelected = user;
                logUser.setText("");
                logPass.setText("");
                vistaPrincipal.pack();
                vistaPrincipal.setLocationRelativeTo(this);
                vistaPrincipal.setVisible(true);
                llenarLista();
                //buscarArbol();
                DefaultMutableTreeNode raiz = new DefaultMutableTreeNode();
                for (Canales canales : usuarioSelected.getCanalesSub()) {
                    llenarArbol(raiz, canales);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void creaPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creaPassActionPerformed

    private void listaCanalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCanalesMouseClicked
        if (listaCanales.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                menuListaCanales.show(listaCanales, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_listaCanalesMouseClicked

    private void subscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribirActionPerformed
        if (listaCanales.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel)listaCanales.getModel();
            Canales canal = (Canales)modelo.get(listaCanales.getSelectedIndex());
            usuarioSelected.setCanalSub((Canales)modelo.get(listaCanales.getSelectedIndex()));
            usuarios.guardarArchivo();
            DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Canales");
            Arbolito arbol = new Arbolito((DefaultTreeModel)arbolito.getModel(), usuarioSelected);
            llenarArbol(raiz, canal);
            llenarLista();
        }
    }//GEN-LAST:event_subscribirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        video = new Videos();
        subtit.setEnabled(true);
        subirVideo.setEnabled(false);
        videosDiag.pack();
        videosDiag.setLocationRelativeTo(vistaPrincipal);
        videosDiag.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void subtitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtitActionPerformed
        video.setSubtitulo(videoArea.getText());
        videoArea.setText("");
        subtitulos();
    }//GEN-LAST:event_subtitActionPerformed

    private void subirVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirVideoActionPerformed
        video.setNombre(videoNombre.getText());
        video.setTiempo(Integer.parseInt(videoTiempo.getValue().toString()));
        usuarioSelected.getCanal().setVideo(video);
        videosDiag.setVisible(false);
        usuarios.guardarArchivo();
    }//GEN-LAST:event_subirVideoActionPerformed

    private void arbolitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolitoMouseClicked
        if (evt.isMetaDown()) {
            int row = arbolito.getClosestRowForLocation(evt.getX(), evt.getY());
            arbolito.setSelectionRow(row);
            Object v1 = arbolito.getSelectionPath().getLastPathComponent();
            nodoSeleccionado = (DefaultMutableTreeNode)v1;
            if (nodoSeleccionado.getUserObject() instanceof Videos) {
                video = ((Videos)nodoSeleccionado.getUserObject());
            }
            menuarbol.show(arbolito, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_arbolitoMouseClicked

    private void VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerActionPerformed
        verVideo.pack();
        verVideo.setLocationRelativeTo(vistaPrincipal);
        verVideo.setModal(true);
        verVideo.setVisible(true);
        nombreVideo.setText(video.getNombre());
    }//GEN-LAST:event_VerActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        hilo = new HiloVideo(video, videoBarra, new Date(), areaVerVideo);
        proceso1 = new Thread(hilo);
        proceso1.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private void llenarLista(){
        DefaultListModel modelo = new DefaultListModel();
        boolean suscrito = false;
        for (Usuarios user : usuarios.getUsers()) {
            if (!user.getCanal().getNombre().equals(usuarioSelected.getCanal().getNombre())) {
                for (Canales canales : usuarioSelected.getCanalesSub()) {
                    if (canales.getNombre().equals(user.getCanal().getNombre())) {
                        suscrito = true;
                    }
                }
                if (!suscrito) {
                    modelo.addElement(user.getCanal());
                }
            }
        }
        listaCanales.setModel(modelo);
    }

    private void llenarArbol(DefaultMutableTreeNode raiz, Canales canal) {
        String cat = canal.getCategoría();
        String nom = canal.getNombre();
        boolean estaCat = false;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                if (raiz.getChildAt(i).toString().equals(cat)) {
                    estaCat = true;
                }
            }
        }

        if (estaCat) {
            for (int i = 0; i < raiz.getChildCount(); i++) {
                for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                    if (raiz.getChildAt(i).toString().equals(cat)) {
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(new DefaultMutableTreeNode(canal.getNombre()));
                        for (Videos video : canal.getVideos()) {
                            ((DefaultMutableTreeNode)raiz.getChildAt(i).getChildAt(j)).add(new DefaultMutableTreeNode(video));
                        }
                    }
                }
            }
        } else {
            DefaultMutableTreeNode categ = new DefaultMutableTreeNode(cat);
            DefaultMutableTreeNode nombreCanal = new DefaultMutableTreeNode(canal.getNombre());
            for (Videos video : canal.getVideos()) {
                nombreCanal.add(new DefaultMutableTreeNode(video));
            }
            categ.add(nombreCanal);
            raiz.add(categ);
            DefaultTreeModel modelo = new DefaultTreeModel(raiz);
            modelo.reload();
            arbolito.setModel(modelo);
        }
    }
    

    private void subtitulos() {
        int numero = (int)videoTiempo.getValue() / 10;
        int x = numero - video.getSubtitulos().size();
        if (x == 0) {
            subtit.setEnabled(false);
            subirVideo.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(videosDiag, "Aun le falta agregar " + x + " comentarios");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ver;
    private javax.swing.JTree arbolito;
    private javax.swing.JTextArea areaVerVideo;
    private javax.swing.JTextField creaCanal;
    private javax.swing.JComboBox<String> creaCat;
    private javax.swing.JTextField creaCorreo;
    private javax.swing.JSpinner creaEdad;
    private javax.swing.JTextField creaNom;
    private javax.swing.JPasswordField creaPass;
    private javax.swing.JTextField creaUser;
    private javax.swing.JDialog crearUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listaCanales;
    private javax.swing.JPasswordField logPass;
    private javax.swing.JTextField logUser;
    private javax.swing.JPopupMenu menuListaCanales;
    private javax.swing.JPopupMenu menuarbol;
    private javax.swing.JLabel nombreVideo;
    private javax.swing.JButton subirVideo;
    private javax.swing.JMenuItem subscribir;
    private javax.swing.JButton subtit;
    private javax.swing.JDialog verVideo;
    private javax.swing.JTextArea videoArea;
    private javax.swing.JProgressBar videoBarra;
    private javax.swing.JTextField videoNombre;
    private javax.swing.JSpinner videoTiempo;
    private javax.swing.JDialog videosDiag;
    private javax.swing.JDialog vistaPrincipal;
    // End of variables declaration//GEN-END:variables
    private Usuarios usuarioSelected = null;
    private adminUsuarios usuarios = new adminUsuarios("./Usuarios.LTube");
    private Videos video = new Videos();
    private DefaultMutableTreeNode nodoSeleccionado;
    HiloVideo hilo = new HiloVideo(video, videoBarra, new Date(), areaVerVideo);
    Thread proceso1;
}
